openapi: 3.0.0
# revisar los nombre de funciones en  Fn::Sub
paths:
  /account/{account-id}:
    get:
      sumarry: Returns the information of an account
      parameters:
        - name: account-id
          in: path
          required: true
          description: account ID
        - in: query
          name: string
          schema:
            type: string
          description: the account ID
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getAccountInformation/invocations"
        httpMethod: "POST"
    put: 
      summary: This saves an account's information
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                account_id:
                  type: string
                name:
                  type: string
                money_amount:
                  type: number
                business_info:
                  type: string
                monthly_salary:
                  type: number
                daily_transactions:
                  type: number
                  
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putNewAccount/invocations"
        httpMethod: "POST"                  
                  
        
  /transaction/{transaction-id}:
    get:
      sumarry: Returns the information of a transaction
      parameters:
        - name: transaction-id
          in: path
          required: true
          description: transaction 
        - in: query
          name: string
          required: true
          description: transaction ID
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getTransactionInformation/invocations"
        httpMethod: "POST"
    put: 
      sumarry: Saves the information of a transaction
      parameters: 
        - name: transaction-id
          in: path
          required: true
          description: transaction's information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender: 
                  type: string
                receiver: 
                  type: string
                amount:
                  type: number
                
             
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putTransactionInformation/invocations"
        httpMethod: "POST"