AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  
Description: Bank
Resources: 
  CompaniesBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref 'arn:aws:s3:::my-bucket-proyect-ale'
      AccessControl: PublicReadWrite
      
  CompaniesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CompaniesBucket
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref CompaniesBucket, /*]]
      
      
  
  
    
    CompanyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: companies_role
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:s3:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AWSOpsWorksCloudWatchLogs'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: lambda-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            Resource: arn:aws:logs:*:*:*
            
            

  GetAccountInformation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getAccountInformation
      Environment:
        Variables: 
          BANK_TABLE: !Ref BankTable
      Handler: bank.getAccountInformation
      Runtime: python3.6
      CodeUri: package/
      Policies:
        
        - DynamoDBReadPolicy:
            TableName: !Ref BankTable  
      
      Events: 
        GetAccount: 
          Type: Api
          Properties: 
            RestApiId: !Ref MyAPI
            Path: "/account/{account_id}"
            Method: GET
  
  PutAccountInformation:
    Type: AWS::Serverless::Function
    Properties: 
      FunctionName: putAccountInformation
      Environment:
        Variables:
          BANK_TABLE: !Ref BankTable
      Handler: bank.putAccountInformation
      Runtime: python3.6
      CodeUri: package/
      Policies: 
        - DynamoDBWritePolicy:
            TableName: !Ref BankTable
      Events:
        PutAccount:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/account/{account_id}""
            Method: PUT
            
  GetIfCompanyIsVerified:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getIfCompanyIsVerified
      Environment:
        Variables: 
          COMPANIES_TABLE: !Ref CompaniesTable
          COMPANIES_BUCKET: !Ref my-bucket-proyect-ale
      Handler: bank.getIfCompanyIsVerified
      Runtime: python3.6
      CodeUri: package/
      
      Role: !GetAtt CompanyRole.Arn
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref CompaniesTable  
       
      Events: 
        GetAccount: 
          Type: Api
          Properties: 
            RestApiId: !Ref MyAPI
            Path: "/company/{company_id}"
            Method: GET
  
  # PutVerifiedCompany:
  #   Type: AWS::Serverless::Function
  #   Properties: 
  #     FunctionName: putVerifiedCompany
  #     Environment:
  #       Variables:
  #         BANK_TABLE: !Ref BankTable
  #     Handler: bank.putVerifiedCompany
  #     Runtime: python3.6
  #     CodeUri: package/
  #     Policies: 
  #       - DynamoDBWritePolicy:
  #           TableName: !Ref BankTable
  #     Events:
  #       PutAccount:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref MyAPI
  #           Path: "/company/{company_id}"
  #           Method: PUT
            
  GetTransactionInformation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTransactionInformation
      Environment:
        Variables: 
          BANK_TABLE: !Ref BankTable
      Handler: bank.getTransactionInformation
      Runtime: python3.6
      CodeUri: package/
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref BankTable  
      Events: 
        GetAccount: 
          Type: Api
          Properties: 
            RestApiId: !Ref MyAPI
            Path: "transaction/{transaction-id}"
            Method: GET
  
  PutTransactionInformation:
    Type: AWS::Serverless::Function
    Properties: 
      FunctionName: putTransactionInformation
      Environment:
        Variables:
          BANK_TABLE: !Ref BankTable
      Handler: bank.putTransactionInformation
      Runtime: python3.6
      CodeUri: package/
      Policies: 
        - DynamoDBWritePolicy:
            TableName: !Ref BankTable
      Events:
        PutAccount:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "transaction/{transaction-id}"
            Method: PUT
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: bank-api
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

  BankTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bank-table
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
      KeySchema:
        - AttributeName: "pk"
          KeyType: HASH
        - AttributeName: "sk"
          KeyType: RANGE
      
      AttributeDefinitions:
        - AttributeName:  "pk"
          AttributeType: S
        - AttributeName: "sk"
          AttributeType: S  
        
  CompaniesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: company_table
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
      KeySchema:
        - AttributeName: "pk"
          KeyType: HASH

      
      AttributeDefinitions:
        - AttributeName:  "pk"
          AttributeType: S
